<script type="text/javascript">
    new (Class.create({
        loadingImageUrl: '<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif');?>',
        method: null,
        initialize: function() {
            var self = this;
            checkout.observe('shippingMethodsUpdated', function(){
                self.onShippingChange();
            });
            this.bind('click', /^s_method.+$/i, this.onShippingChange);
            this.bind('change', /^intime-form-city-field$/i, this.onChangeCity);
            this.bind('change', /^intime-form-warehouse-field$/i, this.onChangeWarehouse);
            this.onShippingChange();

        },
        bind: function(eventType, elementIdRegExp, cb) {
            document.addEventListener(eventType, function (event) {
                var el = event.target
                    , found;
                while (el && !(found = el.id.match(elementIdRegExp))) {
                    el = el.parentElement;
                }
                if (found) {
                    cb.call(this, el, event);
                }
            }.bind(this));
        },
        onShippingChange: function(el, event) {
            var hideForm = true;
            $$('.shipping-method input[type=radio]').each(function(el){
                if (el.id.match(/^s_method_intime/) && el.checked) {
                    hideForm = false;
                    this.method = el.value;
                    this.showForm(Element.up(el, 'li'));
                }
            }.bind(this));
            if (hideForm) {
                this.hideForm();
            }
        },
        showForm: function(formContainer, method) {
            this.showLoading(formContainer);
            new Ajax.Request('<?php echo $this->getUrl('intime/checkout/form')?>', {
                parameters: {method: this.method},
                onSuccess: function(response) {
                    this.hideLoading();
                    this.updateForm(response.responseText, formContainer);
                }.bind(this)
            });
        },
        hideForm: function () {
            if ($('intime-form')) {
                Element.remove('intime-form');
            }
        },
        onChangeCity: function(el) {
            this.showLoading();
            el.disabled = true;
            new Ajax.Request('<?php echo $this->getUrl('intime/checkout/form')?>', {
                parameters: {city: el.value, method: this.method},
                onSuccess: function(response) {
                    this.hideLoading();
                    this.updateForm(response.responseText);
                    el.disabled = false;
                }.bind(this)
            });
        },
        onChangeWarehouse: function(el) {
//            this.showLoading();
//            new Ajax.Request('<?php //echo $this->getUrl('intime/checkout/calculate')?>//', {
//                parameters: {warehouse:el.value},
//                onSuccess: function(response) {
//                    var result = eval('('+response.responseText+')');
//                    this.showDeliveryDateAndCost(result['delivery_date'] || null, result['cost'] || null);
//                    this.hideLoading();
//                }.bind(this)
//            });
        },
        updateForm: function(html, formContainer) {
            var currentForm = $('intime-form');
            if (!formContainer && currentForm) {
                formContainer = currentForm.parentNode;
            }
            if (!formContainer) {
                return;
            }
            if (currentForm) {
                currentForm.parentNode.removeChild(currentForm);
            }
            Element.insert(formContainer, html);
            jQuery($('intime-form')).find('select').uniform({
                selectAutoWidth : false
            });
        },
        showLoading: function(formContainer) {
            if (!formContainer) {
                var currentForm = $('intime-form');
                if (currentForm) {
                    formContainer = currentForm.parentNode;
                }
            }
            if (!formContainer) {
                return;
            }

            var dateAndCost = $('intime-delivery-date-cost');
            if (dateAndCost) {
                dateAndCost.parentNode.removeChild(dateAndCost);
            }

            Element.insert(formContainer, '<p style="display: block;margin: 10px 0" id="intime-loading"><img style="display: inline;vertical-align: middle" height="24" src="'+this.loadingImageUrl+'" alt="" /> <span style="display: inline"><?php echo $this->__('Loading, please wait...');?></span></p>');
        },
        hideLoading: function() {
            Element.remove('intime-loading');
        },
        showDeliveryDateAndCost: function(date, cost) {
            var formContainer = $('intime-form').parentNode;
            checkout.shippingChangedEvent();
            if (date) {
                Element.insert(formContainer, '<div id="intime-delivery-date-cost"><p><span id="intime-delivery-date"><span><?php echo $this->__('Delivery Date')?>:</span> <strong>'+date+'</strong></span></p><p><span id="intime-delivery-cost"><span><?php echo $this->__('Shipping Price')?>:</span> <strong>'+cost+'</strong></span></p></div>');
            } else {
                Element.insert(formContainer, '<div id="intime-delivery-date-cost"><p><span id="intime-delivery-cost"><span><?php echo $this->__('Shipping Price')?>:</span> <strong>'+cost+'</strong></span></p></div>');
            }

        }
    }))();
</script>
